version: "3.9"

name: ric-databridge   # 👈 isolates this stack

services:

  databridge-fastapi:
    build: .
    container_name: ric_databridge_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - databridge-db
    networks:
      - ric-databridge-network

  databridge-frontend:
    build: ./frontend
    container_name: ric_databridge_frontend
    restart: unless-stopped
    networks:
      - ric-databridge-network

  databridge-db:
    image: postgres:18.3
    container_name: ric_databridge_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - databridge_db_data:/var/lib/postgresql/data
    networks:
      - ric-databridge-network

  databridge-nginx:
    image: nginx:latest
    container_name: ric_databridge_nginx
    restart: unless-stopped
    ports:
      - "8081:80"   # 👈 IMPORTANT (unique port!)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - databridge-fastapi
    networks:
      - ric-databridge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  databridge_db_data:

networks:
  ric-databridge-network:
    driver: bridge